#####################################################
# TYE CONFIGURATION
#####################################################

name: tempore

#####################################################
# SERVICES
#####################################################

services:

#----------------------------------------------------
# tempore-auth-storage
#----------------------------------------------------
- name: tempore-auth-storage
  image: postgres:14.6
  bindings:
  - port: 5001
    containerPort: 5432
    protocol: tcp
  env:
  - name: POSTGRES_USER
    value: sa
  - name: POSTGRES_PASSWORD
    value: tempore-123!
  - name: POSTGRES_DB
    value: keycloak
 # TODO: Create database on boot instead this.
  volumes:
  - name: tempore-auth-storage-postgres-data
    target: /var/lib/postgresql/data

#----------------------------------------------------
# tempore-storage
#----------------------------------------------------
- name: tempore-storage
  image: postgres:14.6
  bindings:
  - port: 5002
    containerPort: 5432
    protocol: tcp
  env:
  - name: POSTGRES_USER
    value: sa
  - name: POSTGRES_PASSWORD
    value: tempore-123!
  - name: POSTGRES_DB
    value: tempore
 # TODO: Create database on boot instead this.
  volumes:
  - name: tempore-storage-postgres-data
    target: /var/lib/postgresql/data

#----------------------------------------------------
# tempore-auth
#----------------------------------------------------
- name:  tempore-keycloak
  image: quay.io/keycloak/keycloak:21.0.1
  args: start-dev
  bindings:
  - port: 5003
    containerPort: 8080
    protocol: http
  env:
  - name: DEV_TEST
    value: true
  - name: VERBOSE_LOGGING
    value: true
  - name: DISABLE_TRUST_STORE
    value: true
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: tempore-123!
  - name: KC_DB
    value: postgres
  - name: KC_DB_URL_HOST
    value: host.docker.internal
  - name: KC_DB_URL_PORT
    value: 5001
  - name: KC_DB_URL_DATABASE
    value: keycloak
  - name: KC_DB_USERNAME
    value: sa
  - name: KC_DB_PASSWORD
    value: tempore-123!
  - name: KC_TRANSACTION_XA_ENABLED   
    value: false
  - name: KC_HOSTNAME_STRICT
    value: false
  - name: KC_HTTP_ENABLED
    value: true
  - name: KC_HTTP_PORT
    value: 8080
  - name: KC_HTTP_RELATIVE_PATH
    value: /auth
  - name: KC_PROXY
    value: passthrough
  - name: QUARKUS_HTTP_LIMITS_MAX_HEADER_SIZE
    value: 128K
  - name: QUARKUS_HTTP_LIMITS_MAX_INITIAL_LINE_LENGTH
    value: 8192
  volumes:
  - name: tempore-auth-data
    target: /opt/keycloak/standalone/data/